export default [
        { text: "All", value: -2 },
        { text: "API種別：Dbgl API direct", value: 0 },
        { text: "DbguSystemEvent()", value: (1 << 16) },
        { text: "DbguServiceCall()", value: (2 << 16) },
        { text: "DbguScenarioStart()", value: (3 << 16) }, 
        { text: "DbguScenarioStep()", value: (4 << 16) },
        { text: "DbguProhibitionTable()", value: (5 << 16) },
        { text: "DbguDataWrite()", value: (6 << 16) },
        { text: "DbguScenarioExecute()", value: (7 << 16) },
        { text: "DbguResponse()", value: (8 << 16) },
        { text: "DbguDataChanged()", value: (9 << 16) },
        { text: "DbguCancelResponse()", value: (10 << 16) },
        { text: "DbguScenarioCancel()", value: (11 << 16) },
        { text: "DbguStartDelegation()", value: (12 << 16) },
        { text: "DbguEndDelegation()", value: (13 << 16) },
        { text: "DbguServiceCallback()", value: (14 << 16) },
        { text: "DbguSignal()", value: (15 << 16) },
        { text: "DbguTrace()", value: (16 << 16) },
        { text: "DbguInputTrigger()", value: (17 << 16) },
        { text: "DbguPeripheralStart()", value: (18 << 16) },
        { text: "DbguPeripheralEnd()", value: (19 << 16) },
        { text: "DbguIPC()", value: (32 << 16) },
        { text: "DbguGuiIPC()", value: (33 << 16) },
        { text: "DbguServiceCallGui()", value: (34 << 16) },
        { text: "DbguTraceGui()", value: (35 << 16) },
        { text: "DbguSystemEventGui()", value: (36 << 16) },
        { text: "DbguDriverCallGui()", value: (37 << 16) },
        { text: "DbguDriverCallService()", value: (38 << 16) },
        { text: "DbguDriverCallback()", value: (39 << 16) },
        { text: "DbguScenarioEnd()", value: (40 << 16) },
        { text: "DbguTraceCheckPoint()", value: (41 << 16) },
        { text: "DbguDataLog()", value: ( 42 << 16) },
        { text: "DbguGuiDataLog()", value: (43 << 16) },
        { text: "PF type", value:  -1 },
]
