export const UPDATE_TOOLBAR_MENU = 'UPDATE_TOOLBAR_MENU'

export const UPDATE_TOOLBAR_COMPONENT = 'UPDATE_TOOLBAR_COMPONENT'

export const SHOW_PROCESS_PROGRESS = 'SHOW_PROCESS_PROGRESS'

export const HIDE_PROCESS_PROGRESS = 'HIDE_PROCESS_PROGRESS'

export const SHOW_POPUP_MESSAGE = 'SHOW_POPUP_MESSAGE'

export const HIDE_POPUP_MESSAGE = 'HIDE_POPUP_MESSAGE'

export const UPDATE_CVLOG_OBJECT = 'UPDATE_CVLOG_OBJECT'

export const UPDATE_CVLOG_SEARCH_OBJECT = 'UPDATE_CVLOG_SEARCH_OBJECT'

export const UPDATE_CVLOG_SEARCH_TASK_ID = 'UPDATE_CVLOG_SEARCH_TASK_ID'

export const SHOW_BOTTOM_CONTAINER = 'SHOW_BOTTOM_CONTAINER'

export const HIDE_BOTTOM_CONTAINER = 'HIDE_BOTTOM_CONTAINER'

export const TRIGGER_BOTTOM_CONTAINER = 'TRIGGER_BOTTOM_CONTAINER'
