export const UPDATE_TOOLBAR_MENU = 'UPDATE_TOOLBAR_MENU'

export const UPDATE_TOOLBAR_COMPONENT = 'UPDATE_TOOLBAR_COMPONENT'

export const SHOW_PROCESS_PROGRESS = 'SHOW_PROCESS_PROGRESS'

export const HIDE_PROCESS_PROGRESS = 'HIDE_PROCESS_PROGRESS'

export const SHOW_POPUP_MESSAGE = 'SHOW_POPUP_MESSAGE'

export const HIDE_POPUP_MESSAGE = 'HIDE_POPUP_MESSAGE'

export const UPDATE_CVLOG_OBJECT = 'UPDATE_CVLOG_OBJECT'

export const UPDATE_CVLOG_SEARCH_OBJECT = 'UPDATE_CVLOG_SEARCH_OBJECT'

export const UPDATE_CVLOG_SEARCH_TASK_ID = 'UPDATE_CVLOG_SEARCH_TASK_ID'

export const SHOW_SEARCH_CONTAINER = 'SHOW_SEARCH_CONTAINER'

export const HIDE_SEARCH_CONTAINER = 'HIDE_SEARCH_CONTAINER'

export const TRIGGER_SEARCH_CONTAINER = 'TRIGGER_SEARCH_CONTAINER'

export const UPDATE_EXPORT_PROGRESS = 'UPDATE_EXPORT_PROGRESS'

export const SHOW_SEARCH_DIALOG = 'SHOW_SEARCH_DIALOG'

export const HIDE_SEARCH_DIALOG = 'HIDE_SEARCH_DIALOG'

export const SHOW_GOTO_DIALOG = 'SHOW_GOTO_DIALOG'

export const HIDE_GOTO_DIALOG = 'HIDE_GOTO_DIALOG'
