export const UPDATE_TOOLBAR_MENU = 'UPDATE_TOOLBAR_MENU'

export const UPDATE_TOOLBAR_COMPONENT = 'UPDATE_TOOLBAR_COMPONENT'

export const SHOW_PROCESS_PROGRESS = 'SHOW_PROCESS_PROGRESS'

export const HIDE_PROCESS_PROGRESS = 'HIDE_PROCESS_PROGRESS'
